import { PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn } from 'typeorm';

/**
 * BaseEntity
 * ----------
 * This abstract class defines common columns that almost all database tables
 * in Ziva BI will share:
 * - id: a generated primary key (UUID) to uniquely identify each record.
 * - createdAt: when the record was first created.
 * - updatedAt: when the record was last changed.
 *
 * Other entities (User, Tenant, ExpenseRequest, etc.) will "extend" this class
 * to automatically inherit these standard fields.
 */
export abstract class BaseEntity {
  /**
   * id
   * --
   * This is a UUID primary key, automatically generated by the database.
   * It uniquely identifies each row in a table.
   */
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  /**
   * createdAt
   * ---------
   * The exact date and time (in UTC) when this record was created.
   * TypeORM automatically sets this value when a new row is inserted.
   */
  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt!: Date;

  /**
   * updatedAt
   * ---------
   * The exact date and time (in UTC) when this record was last updated.
   * TypeORM automatically updates this value on each change.
   */
  @UpdateDateColumn({ name: 'updated_at', type: 'timestamptz' })
  updatedAt!: Date;
}
